# Generated by Django 3.0.5 on 2020-05-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMProduct',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50)),
            ],
        ),
    ]
